title: Ogle County Economic Development Corporation
author:
  name: Ogle County EDC
  email: 'info@oglecoedg.org'
metadata:
  description: 'Ogle County Economic Development Corporation - Building economic prosperity in Northern Illinois. Strategic location on I-39 and US Route 20, just 2 hours from Chicago.'
taxonomy:
  - category
  - tag

