home:
  alias: '/home'

pages:
  theme: quark

cache:
  enabled: true
  check:
    method: file

assets:
  css_pipeline: false
  js_pipeline: false
  enable_asset_timestamp: false

errors:
  display: true
  log: true

debugger:
  enabled: false
  provider: clockwork

gpm:
  releases: testing
  verify_peer: true

updates:
  safe_upgrade: true
  safe_upgrade_snapshot_limit: 5
