defaults:
  type: file
  thumb: media/thumb.png
  mime: application/octet-stream
  image:
    filters:
      default:
        - enableProgressive

jpg:
  type: image
  thumb: media/thumb-jpg.png
  mime: image/jpeg
jpe:
  type: image
  thumb: media/thumb-jpg.png
  mime: image/jpeg
jpeg:
  type: image
  thumb: media/thumb-jpeg.png
  mime: image/jpeg
png:
  type: image
  thumb: media/thumb-png.png
  mime: image/png
gif:
  type: animated
  thumb: media/thumb-gif.png
  mime: image/gif

svg:
  type: vector
  thumb: media/thumb-gif.png
  mime: image/svg+xml

mp4:
  type: video
  thumb: media/thumb-mp4.png
  mime: video/mp4
mov:
  type: video
  thumb: media/thumb-mov.png
  mime: video/quicktime
m4v:
  type: video
  thumb: media/thumb-m4v.png
  mime: video/x-m4v
swf:
  type: video
  thumb: media/thumb-swf.png
  mime: video/x-flv
flv:
  type: video
  thumb: media/thumb-flv.png
  mime: video/x-flv

mp3:
  type: audio
  thumb: media/thumb-mp3.png
  mime: audio/mp3
ogg:
  type: audio
  thumb: media/thumb-ogg.png
  mime: audio/ogg
wma:
  type: audio
  thumb: media/thumb-wma.png
  mime: audio/wma
m4a:
  type: audio
  thumb: media/thumb-m4a.png
  mime: audio/m4a
wav:
  type: audio
  thumb: media/thumb-wav.png
  mime: audio/wav
aiff:
  type: audio
  mime: audio/aiff
aif:
  type: audio
  mime: audio/aif

txt:
  type: file
  thumb: media/thumb-txt.png
  mime: text/plain
xml:
  type: file
  thumb: media/thumb-xml.png
  mime: application/xml
doc:
  type: file
  thumb: media/thumb-doc.png
  mime: application/msword
docx:
  type: file
  mime: application/msword
xls:
  type: file
  mime: application/vnd.ms-excel
xlt:
  type: file
  mime: application/vnd.ms-excel
xlm:
  type: file
  mime: application/vnd.ms-excel
xld:
  type: file
  mime: application/vnd.ms-excel
xla:
  type: file
  mime: application/vnd.ms-excel
xlc:
  type: file
  mime: application/vnd.ms-excel
xlw:
  type: file
  mime: application/vnd.ms-excel
xll:
  type: file
  mime: application/vnd.ms-excel
ppt:
  type: file
  mime: application/vnd.ms-powerpoint
pps:
  type: file
  mime: application/vnd.ms-powerpoint
rtf:
  type: file
  mime: application/rtf

bmp:
  type: file
  mime: image/bmp
tiff:
  type: file
  mime: image/tiff
mpeg:
  type: file
  mime: video/mpeg
mpg:
  type: file
  mime: video/mpeg
mpe:
  type: file
  mime: video/mpeg
avi:
  type: file
  mime: video/msvideo
wmv:
  type: file
  mime: video/x-ms-wmv

html:
  type: file
  thumb: media/thumb-html.png
  mime: text/html
htm:
  type: file
  thumb: media/thumb-html.png
  mime: text/html
pdf:
  type: file
  thumb: media/thumb-pdf.png
  mime: application/pdf
zip:
  type: file
  thumb: media/thumb-zip.png
  mime: application/zip
gz:
  type: file
  thumb: media/thumb-gz.png
  mime: application/gzip
tar:
  type: file
  mime: application/x-tar
css:
  type: file
  thumb: media/thumb-css.png
  mime: text/css
js:
  type: file
  thumb: media/thumb-js.png
  mime: application/javascript
json:
  type: file
  thumb: media/thumb-json.png
  mime: application/json

