absolute_urls: false                   # Absolute or relative URLs for `base_url`

home:
  alias: '/home'                       # Default path for home, ie /

pages:
  theme: antimatter                    # Default theme (defaults to "antimatter" theme)
  markdown_extra: false                # Enable support for Markdown Extra support (GFM by default)
  order:
    by: defaults                       # Order pages by "default", "alpha" or "date"
    dir: asc                           # Default ordering direction, "asc" or "desc"
  list:
    count: 20                          # Default item count per page
  dateformat:
    short: 'jS M Y'                    # Short date format
    long: 'F jS \a\t g:ia'             # Long date format
  process:
    markdown: true                     # Process Markdown
    twig: false                        # Process Twig
  events:
    page: true                         # Enable page level events
    twig: true                         # Enable twig level events

cache:
  enabled: true                        # Set to true to enable caching
  check:
    method: file                       # Method to check for updates in pages: file|folder|none
  driver: auto                         # One of: auto|file|apc|xcache|memcache|wincache
  prefix: 'g'                          # Cache prefix string (prevents cache conflicts)

twig:
  cache: true                          # Set to true to enable twig caching
  debug: false                         # Enable Twig debug
  auto_reload: true                    # Refresh cache on changes
  autoescape: false                    # Autoescape Twig vars

assets:                                # Configuration for Assets Manager (JS, CSS)
  css_pipeline: false                  # The CSS pipeline is the unification of multiple CSS resources into one file
  css_minify: true                     # Minify the CSS during pipelining
  css_minify_windows: false            # Minify Override for Windows platforms. False by default due to ThreadStackSize
  css_rewrite: true                    # Rewrite any CSS relative URLs during pipelining
  js_pipeline: false                   # The JS pipeline is the unification of multiple JS resources into one file
  js_minify: true                      # Minify the JS during pipelining

errors:
  display: true                        # Display full backtrace-style error page
  log: true                            # Log errors to /logs folder

debugger:
  enabled: false                       # Enable Grav debugger and following settings
  twig: true                           # Enable debugging of Twig templates
  shutdown:
    close_connection: true             # Close the connection before calling onShutdown(). false for debugging
