language: php
php: 5.6
branches:
  only:
    - master
    - build_test
notifications:
  email:
    on_success: never
    on_failure: always
  hipchat:
  # hipchat_api@grav
    rooms:
      - secure: "bqO0wM1B7bJnQw2fuhquSXEqI9gw6WmFytIh9sEWXzbYTzTUP5t0PcKOd3FT2BNMRaDxPJLVl+vG/oqmqDUBkEmOGcG504IQjeNzZqnMz0tXQMIcCc22Las9tFfc4Jf6RVi/qGomFtHGE9Wgii+TAN4zqZaufbNjwd8SyjO0+W8="
    template:
      - '%{repository}#%{build_number} (%{branch}): Grav Core and Skeletons packages have been uploaded. (<a href="%{build_url}">Details</a>)'
    format: html
env:
  global:
    # Colors!
    - TEXTRESET=$(tput sgr0) # reset the foreground colour
    - RED=$(tput setaf 1)
    - GREEN=$(tput setaf 2)
    - YELLOW=$(tput setaf 3)
    - BLUE=$(tput setaf 4)
    - BOLD=$(tput bold)
    # User
    - GH_USER="getgrav"
    # Paths
    - RT_DEVTOOLS=$HOME/devtools
    - GOPATH="$HOME/go"
    - PATH="$GOPATH/bin:$PATH"
    # GH_TOKEN [API Key]
    - secure: "jS+c+g2v33vypG4VtqiSDW2qQ4dGJZlrUKBRCztoy1yrOrYRPvc5Vzi/AS3fDmZ4yizukEwmUNNzyZQcgFvLPpmCCml46Dovp8R9OXhbNe8OnULmaSn2Zkr71oblMYu6ZP+RpYvNq0BIdSB3u2TiFriHMiTIkX9UwZNaUCOX1ig="
    # BB_TOKEN value => "user:pass@"
    - secure: "einUtSEkUWy2IrqLXyVjwUU+mwaaoiOXRRVdLBpA3Zye6bZx8cm5h/5AplkPWhM/NmCJoW/MwNZHHkFhlr3mDRov5iOxVmTTYfnXB+I5lxYTSgduOLLErS7mU8hfADpVDU8bHNU44fNGD3UEiG1PD4qQBX4DMlqIFmR20mjs81k="
    # GH_API_USER [for curl]
    - secure: "Xbk/V9aIys0NxccJGR3Zrm2GRxDnA0RuazBs1puIboTYDhbi0Z7JTL+mOx3xp5Kfoniad/xAuijQESTM9MMrKqq/qCzhAMaC1+vcL4pCHZH4NSG6DBxB9BPkKVFq+1llu5FTEf8bkxHzwGR0l1ARW6TVRcgTHr5B58bCEIwEOrI="
    # Latest Release version
    - TRAVIS_TAG=$(curl --fail --user ${GH_API_USER} -s https://api.github.com/repos/getgrav/grav/releases/latest | grep tag_name | head -n 1 | cut -d '"' -f 4)

before_install:
  - export TZ=Pacific/Honolulu
  - composer self-update
  - go get github.com/aktau/github-release
  - echo "Travis Date - `date`"
  - git clone --quiet --depth=50 --branch=master https://${BB_TOKEN}bitbucket.org/rockettheme/grav-devtools.git $RT_DEVTOOLS  &>/dev/null;
  - if [ ! -z "$TRAVIS_TAG" ]; then
      cd "${RT_DEVTOOLS}";
      ./build-grav.sh skeletons.txt;
    fi
script:
  - if [ ! -z "$TRAVIS_TAG" ]; then
      FILES="$RT_DEVTOOLS/grav-dist/*.zip";
      for file in ${FILES[@]}; do
        NAME=${file##*/};
        if [[ "$NAME" == *"-rc"* ]]; then
            REPO="$(echo ${NAME} | rev | cut -f 3- -d "-" | rev)";
        else
            REPO="$(echo ${NAME} | rev | cut -f 2- -d "-" | rev)";
        fi;
        if [[ $REPO == 'grav' || $REPO == 'grav-admin' || $REPO == 'grav-update' ]]; then
          REPO="grav";
        fi;
        API="$(curl --fail --user "${GH_API_USER}" -s https://api.github.com/repos/${GH_USER}/${REPO}/releases/latest)";
        ASSETS="$(echo "${API}" | node gh-assets.js)";
        TAG="$(echo "${API}" | grep tag_name | head -n 1 | cut -d '"' -f 4)";
        if [ $REPO == "grav" ]; then
          TAG="$TRAVIS_TAG";
        fi;
        if [ ! -z "$ASSETS" ]; then
          for asset in ${ASSETS[@]}; do
            asset_id=$(echo ${asset} | cut -d ':' -f 1);
            asset_name=$(echo ${asset} | cut -d ':' -f 2);
            if [ "${NAME}" == "${asset_name}" ]; then
              echo -e "\nAsset ${BOLD}${BLUE}${NAME}${TEXTRESET} already exists in ${YELLOW}${REPO}${TEXTRESET}@${BOLD}${YELLOW}${TAG}${TEXTRESET}... deleting id ${BOLD}${RED}${asset_id}${TEXTRESET}...";
              curl -X DELETE --fail --user "${GH_API_USER}" "https://api.github.com/repos/${GH_USER}/${REPO}/releases/assets/${asset_id}";
            fi;
          done;
        fi;
        echo "Uploading package ${BOLD}${BLUE}${NAME}${TEXTRESET} to ${YELLOW}${REPO}${TEXTRESET}@${YELLOW}${TAG}${TEXTRESET}";
        github-release upload --security-token $GH_TOKEN --user ${GH_USER} --repo $REPO --tag "$TAG" --name "$NAME" --file "$file";
      done;
    fi
