enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: true
  icons: true
custom_logo:
  -
    name: afj.png
custom_logo_mobile:
  -
    name: afj.png
