streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/local, user/themes/minimal, user/themes/quark-open-publishing, user/themes/quark]
chromeless:
  enabled: false
display_of_git_sync_repo_link: none
type_of_git_sync_repo_link: view
h5pembedrootpath: 'https://h5p.org/h5p/embed/'
displaycustommenus:
  enabled: false
hidehomemenulink: true
production-mode: true
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /tutorial
spectre:
  exp: false
  icons: false
grid-size: grid-lg
menu:
  -
    text: Grav
    icon: arrow-circle-right
    url: 'https://getgrav.org/'
    target: _blank
dropdown:
  enabled: false
blog_page_hero_classes: 'text-light title-h1h2 overlay-dark-gradient hero-large parallax'
